services:
  agent:
    build:
        context: ./openflare-server
        dockerfile: docker/Dockerfile.agent
    container_name: openflare-agent
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:18081:18081"

    volumes:
      - ./data/agent/:/data

    environment:
      OPENFLARE_SERVER_URL: "http://host.docker.internal:3000"
      OPENFLARE_AGENT_TOKEN: "ce5a664631a7c5c54d3406a376847535"
      LOG_LEVEL: "debug"

    extra_hosts:
      - "host.docker.internal:host-gateway"

  relay:
    build:
      context: ./openflare-server
      dockerfile: docker/Dockerfile.relay
    container_name: openflare-relay
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data/relay/:/app/data
    environment:
      OPENFLARE_SERVER_URL: http://host.docker.internal:3000
      OPENFLARE_DISCOVERY_TOKEN: 85464eeb72c49abc430569d6b9c77f78
      LOG_LEVEL: "debug"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  flared:
    build:
      context: ./openflare-server
      dockerfile: docker/Dockerfile.flared
    container_name: openflare-flared
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./data/flared/:/app/data
    environment:
      OPENFLARE_SERVER_URL: "http://host.docker.internal:3000"
      OPENFLARE_TUNNEL_TOKEN: deb0783ac1e264a9d86440169aca0f09


