services:
  agent:
    build:
        context: .
        dockerfile: openflare-agent/Dockerfile
    container_name: openflare-agent
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:18081:18081"

    volumes:
      - ./openflare-agent/data/:/data

    environment:
      OPENFLARE_SERVER_URL: "http://host.docker.internal:3000"
      OPENFLARE_AGENT_TOKEN: "111675c3b22c8cf39b43639b9305fa0a"
      LOG_LEVEL: "debug"

    extra_hosts:
      - "host.docker.internal:host-gateway"

  relay:
    build:
      context: .
      dockerfile: openflare-relay/Dockerfile
    container_name: openflare-relay
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./openflare-relay/data/:/app/data
    environment:
      OPENFLARE_SERVER_URL: http://host.docker.internal:3000
      OPENFLARE_DISCOVERY_TOKEN: 85464eeb72c49abc430569d6b9c77f78
      LOG_LEVEL: "debug"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  flared:
    build:
      context: .
      dockerfile: openflared/Dockerfile
    container_name: openflare-flared
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./openflared/data/:/app/data
    environment:
      OPENFLARE_SERVER_URL: "http://host.docker.internal:3000"
      OPENFLARE_TUNNEL_TOKEN: deb0783ac1e264a9d86440169aca0f09

